### ISSUE TITLE
File constituents-financials_csv.csv is missing

### ISSUE THREAD

**Issue by schalkk** [dataenq/Data#1]
Hi, 

In you R-Code, the last steps to verify the merged table. you refere to a file called "constituents-financials_csv.csv"  This file sis not available in the repository.

Thanks in advance!

Regards,
Schalk

**Comment by dataenq** [comment]
Hello there,

Sorry about that. Here is the link for the file. [constituents-financials_csv.csv](https://github.com/dataenq/Data/blob/master/constituents-financials_csv.csv)

**Comment by dataenq** [comment]
File uploaded and available [here](https://github.com/dataenq/Data/blob/master/constituents-financials_csv.csv)
